In [ ]:
import torch
from torch import nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
breast_cancer = load_breast_cancer()

In [ ]:
data1 = pd.DataFrame(data=breast_cancer.data, columns=breast_cancer.feature_names)
data1["target"] = breast_cancer.target

In [ ]:
data1.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [ ]:
data1['target'].value_counts()

1    357
0    212
Name: target, dtype: int64

In [ ]:
X = data1.iloc[:,:-1]

In [ ]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
y = data1.iloc[:,-1]

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [ ]:
X = torch.tensor(X.values).type(torch.float)
y = torch.tensor(y.values).type(torch.float)

In [ ]:
print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

X shape: torch.Size([569, 30])
y shape: torch.Size([569])


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
print(f"X train shape: {X_train.shape}")
print(f"X test shape: {X_test.shape}")
print(f"y train shape: {y_train.shape}")
print(f"y test shape: {y_test.shape}")

X train shape: torch.Size([398, 30])
X test shape: torch.Size([171, 30])
y train shape: torch.Size([398])
y test shape: torch.Size([171])


In [ ]:
class BreastModel(nn.Module):
  def __init__(self):
    super().__init__()

    self.layer_1 = nn.Linear(in_features=5, out_features=8)
    self.layer_2 = nn.Linear(in_features=8, out_features=1)

  def forward(self, x):
    return self.layer_2(self.layer_1(x))

model_1 = BreastModel()
model_1

BreastModel(
  (layer_1): Linear(in_features=5, out_features=8, bias=True)
  (layer_2): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
model_1 = nn.Sequential(
    nn.Linear(in_features=5, out_features=8),
    nn.Linear(in_features=8, out_features=1)
)

model_1

Sequential(
  (0): Linear(in_features=5, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
loss_fn = nn.BCEWithLogitsLoss()

optimizer = torch.optim.SGD(params=model_2.parameters(), lr=0.1)

In [ ]:
def accuracy_fn(y_true, y_pred):
  correct = torch.eq(y_true, y_pred).sum().item()
  acc = (correct / len(y_pred)) * 100
  return acc

In [ ]:
X_train[:1]

tensor([[1.3740e+01, 1.7910e+01, 8.8120e+01, 5.8500e+02, 7.9440e-02, 6.3760e-02,
         2.8810e-02, 1.3290e-02, 1.4730e-01, 5.5800e-02, 2.5000e-01, 7.5740e-01,
         1.5730e+00, 2.1470e+01, 2.8380e-03, 1.5920e-02, 1.7800e-02, 5.8280e-03,
         1.3290e-02, 1.9760e-03, 1.5340e+01, 2.2460e+01, 9.7190e+01, 7.2590e+02,
         9.7110e-02, 1.8240e-01, 1.5640e-01, 6.0190e-02, 2.3500e-01, 7.0140e-02]])

In [ ]:
class BreastCancerClassification(nn.Module):
  def __init__(self):
    super().__init__()

    self.layer_1 = nn.Linear(in_features=30, out_features=128)
    self.layer_2 = nn.Linear(in_features=128, out_features=128)
    self.layer_3 = nn.Linear(in_features=128, out_features=1)

  def forward(self, x):
    return self.layer_3(self.layer_2(self.layer_1(x)))

model_2 = BreastCancerClassification()

model_2

BreastCancerClassification(
  (layer_1): Linear(in_features=30, out_features=128, bias=True)
  (layer_2): Linear(in_features=128, out_features=128, bias=True)
  (layer_3): Linear(in_features=128, out_features=1, bias=True)
)

In [ ]:
model_2.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.0300, -0.1220,  0.0225,  ..., -0.1515, -0.0339, -0.1151],
                      [-0.0493, -0.0052,  0.0332,  ...,  0.0420,  0.1643,  0.0776],
                      [-0.1291, -0.0618, -0.0327,  ..., -0.0783, -0.1331, -0.0126],
                      ...,
                      [-0.0698,  0.0250,  0.0918,  ...,  0.1610, -0.0957, -0.0220],
                      [-0.1078,  0.1695,  0.1113,  ..., -0.0247,  0.0526, -0.1108],
                      [ 0.0045, -0.0944,  0.0657,  ...,  0.0713, -0.0031, -0.1207]])),
             ('0.bias',
              tensor([-0.1180, -0.1041,  0.1166, -0.1203,  0.0815, -0.0892,  0.1068,  0.0114,
                      -0.1287,  0.0899, -0.0710, -0.0361,  0.1516, -0.0484,  0.1436,  0.0758,
                       0.0186, -0.0182,  0.1656,  0.1552,  0.0692, -0.1570, -0.1416,  0.1269,
                       0.1171,  0.1780, -0.0936,  0.0377,  0.0983, -0.0743,  0.0866, -0.0036,
                       0.1561,  0.1497, 

In [ ]:
model_2 = nn.Sequential(
    nn.Linear(in_features=30, out_features=128),
    nn.Linear(in_features=128, out_features=128),
    nn.Linear(in_features=128, out_features=1)
)

model_2

Sequential(
  (0): Linear(in_features=30, out_features=128, bias=True)
  (1): Linear(in_features=128, out_features=128, bias=True)
  (2): Linear(in_features=128, out_features=1, bias=True)
)

In [ ]:
epochs = 50

for epoch in range(epochs):
  model_2.train()

  y_logits_2 = model_2(X_train).squeeze()
  y_pred_2 = torch.round(torch.sigmoid(y_logits_2))

  loss_2 = loss_fn(y_logits_2, y_train)
  accuracy_2 = accuracy_fn(y_true=y_train, y_pred=y_pred_2)

  optimizer.zero_grad()

  loss_2.backward()

  optimizer.step()

  model_2.eval()
  with torch.inference_mode():
    test_logits_2 = model_2(X_test).squeeze()
    test_pred_2 = torch.round(torch.sigmoid(test_logits_2))

    test_loss_2 = loss_fn(test_logits_2, y_test)

    test_accuracy_2 = accuracy_fn(y_true=y_test, y_pred=test_pred_2)

  if epoch % 10 == 0:
    print(f"Epoch: {epoch} | Train Loss: {loss_2:.5f} | Test Loss: {test_loss_2:.5f} | Accuracy: {accuracy_2:.2f} | Test Accuracy: {test_accuracy_2:.2f}")

Epoch: 0 | Train Loss: 6.84635 | Test Loss: 7.21749 | Accuracy: 62.56 | Test Accuracy: 63.16
Epoch: 10 | Train Loss: 6.84635 | Test Loss: 7.21749 | Accuracy: 62.56 | Test Accuracy: 63.16
Epoch: 20 | Train Loss: 6.84635 | Test Loss: 7.21749 | Accuracy: 62.56 | Test Accuracy: 63.16
Epoch: 30 | Train Loss: 6.84635 | Test Loss: 7.21749 | Accuracy: 62.56 | Test Accuracy: 63.16
Epoch: 40 | Train Loss: 6.84635 | Test Loss: 7.21749 | Accuracy: 62.56 | Test Accuracy: 63.16


In [ ]:
'''epochs = 100

for epoch in range(epochs):
  model_1.train()

  y_logits_1 = model_1(X_train).squeeze()
  y_pred = torch.round(torch.sigmoid(y_logits))

  loss = loss_fn(y_logits_1, y_train)
  accuracy = accuracy_fn(y_true = y_train, y_pred = y_pred)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  model_1.eval()
  with torch.inference_mode():
    test_logits = model_1(X_test).squeeze()
    test_pred = torch.round(torch.sigmoid(test_logits))

    test_loss = loss_fn(test_logits, y_test)

    test_accuracy = accuracy_fn(y_true=y_test, y_pred = test_pred)

  if epoch % 10 == 0:
    print(f"Epoch: {epoch} | Train Loss: {loss:.5f} | Accuracy: {accuracy:.2f} | Test Loss: {test_loss:.5f} | Test Accuracy: {test_accuracy:.2f}")'''




'epochs = 100\n\nfor epoch in range(epochs):\n  model_1.train()\n\n  y_logits_1 = model_1(X_train).squeeze()\n  y_pred = torch.round(torch.sigmoid(y_logits))\n\n  loss = loss_fn(y_logits_1, y_train)\n  accuracy = accuracy_fn(y_true = y_train, y_pred = y_pred)\n\n  optimizer.zero_grad()\n\n  loss.backward()\n\n  optimizer.step()\n\n  model_1.eval()\n  with torch.inference_mode():\n    test_logits = model_1(X_test).squeeze()\n    test_pred = torch.round(torch.sigmoid(test_logits))\n\n    test_loss = loss_fn(test_logits, y_test)\n\n    test_accuracy = accuracy_fn(y_true=y_test, y_pred = test_pred)\n\n  if epoch % 10 == 0:\n    print(f"Epoch: {epoch} | Train Loss: {loss:.5f} | Accuracy: {accuracy:.2f} | Test Loss: {test_loss:.5f} | Test Accuracy: {test_accuracy:.2f}")'